### ISSUE TITLE
Revise choice of prompt for windows

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/rsd#128]
What works on command prompt? Git bash? Anaconda prompt?

(Because autocompletion of git commands does not work in Anaconda prompt.)

**Comment by Nikoleta-v3** [comment]
**Regarding autocompletion of git commands**

Autocompletion of git commands do not work in any prompt, neither in anaconda, command or Git CDM, The only way of getting around this is using the `git bash` which comes with the `git` installation. But we will not be teaching command prompt at all.

The second issue was **regarding copy paste in the command prompt**. This is easily resolved by doing this: https://www.isumsoft.com/it/how-to-copy-and-paste-in-command-prompt-on-windows-7-10/

**Comment by drvinceknight** [comment]
> But we will not be teaching command prompt at all.

I don't  believe we currently use the command prompt at all for windows, we recommend anaconda prompt (to ensure python behaves). I think I'll add something recommending `git bash` for git on windows.

**Comment by Nikoleta-v3** [comment]
we use anaconda prompt but we use cmd commands. For example `dir` to display the files in the current directory.

If you use git bash then you are using bash commands. For example `ls` to display the files in the current directory.

**Comment by drvinceknight** [comment]
Ah yes of course!

Does the way I've written it in #138 look ok? Left as is and just mentioned that if you want to use tab completion for git you need to use git bash.

**Comment by Nikoleta-v3** [comment]
I'm going through the `pr`s now!
