### ISSUE TITLE
Test cli and git on Windows

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/rsd#17]
We need to find a Windows machine to install Anaconda prompt as well as git and test the cli chapter and the git chapter.

Once we're happy with the content we'll do a run through with one of us on a Windows box.

**Comment by Nikoleta-v3** [comment]
Have taken the course using my Windows machine.

chapter one.
--------------
 Prompt commands are correct.

chapter two.
--------------
 Python commands and scripts run fine.

chapter four.
--------------
 Installed MiKTex and it compiled the documents just fine with the command `pdflatex main.tex` 

A small note: restart the anaconda prompt after installing MiKTex. 

Also I run the `.py` files for this chapter and did not get an error for the paths :+1: 
Here is the pdf: [main.pdf](https://github.com/drvinceknight/rsd/files/1553752/main.pdf)

chapter five.
-------------
`git`  commands all worked just fine. 

The only issue I had in this chapter is getting atom as a git editor. 
I followed this issue: https://github.com/atom/atom/issues/3074
 and downloaded the latest atom version as suggested by still couldn't get it to work on my machine. I could try a uni one as well.

I got VS code to work just fine but with the following command, adding argument `-n`: 
`git config --global core.editor "'C:\Program Files (x86)\Microsoft VS Code\code.exe' -n --wait"`

**Comment by drvinceknight** [comment]
Super star @Nikoleta-v3 thank you.

Pity about atom... from that issue: 

> This has been fixed and should be out in Atom 1.6.0.

Which doesn't seem to be the case (current version is 1.23+ I think).

> I got VS code to work just fine but with the following command, adding argument -n:

Do you know what the `-n` is for? (Not terribly important, we'll include it anyway).

I think we'll leave both and then have a "if it doesn't work don't worry there will be some editor that works..." (and possibly teach vim or nano or whatever opens on the fly)...

**Comment by Nikoleta-v3** [comment]
yes the `-n` will launch a new window which is just for the commit. Save, close and you're done.

**Comment by drvinceknight** [comment]
Cool :+1:
