### ISSUE TITLE
Find better name for `repeate_divide_number`

### ISSUE THREAD

**Issue by geraintpalmer** [drvinceknight/rsd#44]

**Comment by geraintpalmer** [comment]
`repeat_divide.get_results_and_count` ?

**Comment by drvinceknight** [comment]
`repeat_divide.get_remaining_factor_and_count`?

**Comment by drvinceknight** [comment]
- `is_prime.check` (for what is currently `is_prime.is_prime`.
- `get_factors.obtain` for the other one.

**Comment by drvinceknight** [comment]
Or `prime_factors.get`?

**Comment by geraintpalmer** [comment]
This is a bit out there, so probably inappropriate, but how about changing `reapeat_divide` to:

```
def get_prime_power_of_b(N, b):
    count = 0
    while N >= b and N % b == 0:
        count += 1
        N = N / b
   return count
```

and then `obtain_prime_factorisation` becomes:

```
    factors = []
    potential_factor = 1

    while N > 1:
        potential_factor += 1

        if is_prime.is_prime(potential_factor):

            exponent = get_prime_power_of_b(N, potential_factor)
            N = N / (potential_factor ** exponent)

            if exponent > 0:
                factors.append((potential_factor, exponent))

    return factors
```

?

We would then have better naming, and doing modularisation better (because `get_prime_power_of_b` might be more useful outside of this context than `repeat_divide_number`). And we have each function doing 1 thing good.

**Comment by drvinceknight** [comment]
Yeah I like that. We'll go for that. It's a tiny bit redundant (we're doing the division twice) but much clearer.

**Comment by drvinceknight** [comment]
Although: `get_prime_power_of_b` should be `count_number_of_divisions` or something like that.

**Comment by drvinceknight** [comment]
`get_exponent_of_factor`

**Comment by drvinceknight** [comment]
So:

- `is_prime.check`
- `integer_division.get_exponent_of_factor` (with @geraintpalmer's suggested change)
- `prime_factors.get`

?
