### ISSUE TITLE
Triangle

### ISSUE THREAD

**Issue by geraintpalmer** [drvinceknight/rsd#45]
Modularity - Documentation - Testing

**Comment by Nikoleta-v3** [comment]
![img_20171215_105639](https://user-images.githubusercontent.com/19708408/34039270-ce8b0f22-e186-11e7-8cb8-87897b3b8bcd.jpg)

**Comment by geraintpalmer** [comment]
[good_practice_triangle.pdf](https://github.com/drvinceknight/rsd/files/1563065/good_practice_triangle.pdf)

**Comment by drvinceknight** [comment]
Looks great @geraintpalmer you ok to PR the pdf file and tex code? (I can add it to the docs)

**Comment by geraintpalmer** [comment]
yep, I'll do that Sunday!

**Comment by drvinceknight** [comment]
I reckon should be `makes possible & tests failures become more meaningful` (the `&` matches up with the rest)? (Not terribly bothered)
