### ISSUE TITLE
check that .gitignore appears on windows

### ISSUE THREAD

**Issue by Nikoleta-v3** [drvinceknight/rsd#90]

**Comment by drvinceknight** [comment]
@Nikoleta-v3 could you also check that the command to remove a directory (https://vknight.org/rsd/chapters/01/) works?

**Comment by Nikoleta-v3** [comment]
`.gitignore` appears by just typing `dir`.

![tets_gitignore_w](https://user-images.githubusercontent.com/19708408/34080756-ffa7718a-e33a-11e7-9dd7-25ac61003c2c.png)

**Comment by Nikoleta-v3** [comment]
As for the command `rmdir`. As you can see if there are files within the folder you are getting a `The directory is not empty.`  message. You need to force it with the following command  `rmdir /s`.


![tets_deleting_files](https://user-images.githubusercontent.com/19708408/34080796-7055ed1c-e33b-11e7-944b-9614b2273c2b.png)

**Comment by drvinceknight** [comment]
@Nikoleta-v3 did you check that `xcopy` (the command to copy a dir) works as described in https://vknight.org/rsd/chapters/01/? (Does it need a flag if the dir is not empty?)

**Comment by drvinceknight** [comment]
> nikoleta | no flag needed
